public class Env2 {
    public class Wrapper{
        public Integer statusCode;	    //200
	    public boolean success;
	    public List<response> response;
    }
    public class response{
        public Integer id;
        public String first_name;
        public String middle_name;
        public String last_name;
        public String address1;
        public String address2;
        public String city;
        public String state_id;
        public String country_id;
        public Integer home_country_id;
        public String zip;
        public String dob;
        public String tele;
        public String email;
        public String gender;
        public Integer us_citizen;
        public Integer us_destination;
        public Integer plan_id;
        public Integer status_id;
        public Integer sports_rider;
        public String note;
        public String secondaryEmail;
        public Integer trip_can;
        public String start_date;
        public String end_date;
        public String intermediate_date;
        public String created_date;
        public String updated_date;
        
        public Integer internal_id;
        public Integer travel_days;
        public Integer courtesy_date;
        public Integer underwriter_ext_id;
        public Integer tax_id;
        public Integer visaType;
        public Integer gross_premium;
        public Integer destination_country_id;
        public Integer telemedicine_id; 
 
    }

}