public class Env3 {
    public class Wrapper{
        public Integer statusCode;	    
	    public boolean success;
	    public List<response> response;
    }
    
        public class Response {
		public Integer id;
		public String first_name;
		public String middle_name;
		public String last_name;
		public String address1;
		public String address2;
		public String city;
		public Object state_id;
		public Object country_id;
		public Integer home_country_id;
		public String zip;
		public String dob;
		public String tele;
		public String email;
		public String gender;
		public Integer us_citizen;
		public Integer us_destination;
		public Integer plan_id;
		public Integer status_id;
		public Integer sports_rider;
		public Object note;
		public Object secondaryEmail;
		public Integer trip_can;
		public String start_date;
		public String end_date;
		public Object intermediate_date;
		public String created_date;
		public String updated_date;
		public Object internal_id;
		public Integer travel_days;
		public Object courtesy_date;
		public Object underwriter_ext_id;
		public Object tax_id;
		public Object visaType;
		public Object gross_premium;
		public Object destination_country_id;
		public Object telemedicine_id;
	}

 
 
    



}